### ISSUE TITLE
Best selling items are not imported into lego shopping cart

### ISSUE THREAD

**Issue by langph** [BrickTwo/BrickHunter#191]
When I try to add my items to the shopping cart, only standard items are imported. It appears that the bick a brick page (in Dutch) has been changed somewhat: Now I can see shopping cart totals at the bottom of the page.

**Comment by BrickTwo** [comment]
Should be fixed with Version 1.9.10. It's already available for Firefox but can take some days until it is available for Chrome.

**Comment by sensbo** [comment]
Hi, I have a similar problem. I am using 1.9.10 version at Chrome but still facing the issue at Chrome. Login/logout didn't fix it, only Lego page will be refreshed. I have 25 standard items 150 bestseller items, all will not be added so far :-/ 

 Any idea?

**Comment by BrickTwo** [comment]
yeah I had to push another fix with version 1.9.11 which is already available for Firefox but is waiting to be approved on Chrome

**Comment by mifi1337** [comment]
Hi, for me 1.9.11 didn't solve this issue. I tried Chrome and Firefox, but i have the same behaviour in both browsers.
Bestseller items are not transferred at all. This cart is always empty. The "Standard Item" cart is populated but the result differs always. 
If i transfer always the same partlist, i will always get an different partcount in "standard item" cart.

Is there anything i can do to solve this?

**Comment by BrickTwo** [comment]
can you maybe send me your partlist to info@bricktwo.net ?

**Comment by BrickTwo** [comment]
Fixed with BrickHunter 2.0
